services:
    mongo:
        ports:
            - '27017:27017'
        container_name: mymongo
        # restart: always
        logging:
            options:
                max-size: 1g
        environment:
            - MONGO_INITDB_ROOT_USERNAME=secret
            - MONGO_INITDB_ROOT_PASSWORD=secret
        image: mongo:4.4.18